# Generated by Django 4.1 on 2022-09-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('NW', 'Needs Water')], default='OK', max_length=2),
        ),
    ]
