# Generated by Django 4.1 on 2022-09-08 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='plant_slug',
            new_name='slug',
        ),
    ]
