# Generated by Django 4.1.2 on 2023-11-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(default='bloop', max_length=100),
            preserve_default=False,
        ),
    ]
