# Generated by Django 4.1.2 on 2023-10-10 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
