# Generated by Django 4.1 on 2022-09-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0002_plant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.CharField(choices=[('EOD', 'Every Other Day'), ('OAW', 'Once a Week'), ('ETW', 'Every 2 Weeks'), ('OAM', 'Once a Month')], default='OAW', max_length=3),
        ),
    ]
