# Generated by Django 4.1.2 on 2023-11-13 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_plant_diary.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_plant_diary', '0002_alter_plant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='last_watered',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='next_watering',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='watering_frequency',
        ),
        migrations.AddField(
            model_name='task',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, validators=[my_plant_diary.models.validate_plant_owner]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, validators=[my_plant_diary.models.validate_plant_name]),
        ),
        migrations.AlterField(
            model_name='plant',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL, validators=[my_plant_diary.models.validate_plant_owner]),
        ),
    ]
