# Generated by Django 4.1.2 on 2023-10-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('OK', 'Ok'), ('NA', 'Needs Attention')], default='OK', max_length=2),
        ),
    ]
