# Generated by Django 4.1 on 2022-09-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0003_plant_watering_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(null=True),
        ),
    ]
