# Generated by Django 4.1.2 on 2023-10-31 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0004_task_overdue_alter_plant_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='overdue',
        ),
        migrations.AlterField(
            model_name='task',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='my_plant_diary.plant'),
        ),
    ]
