# Generated by Django 4.1.2 on 2023-11-13 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0004_plant_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='created',
        ),
    ]
