# Generated by Django 4.1.2 on 2023-11-02 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0005_remove_task_overdue_alter_task_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_plant_diary.plant'),
        ),
    ]
