# Generated by Django 4.1.2 on 2023-11-13 18:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0005_remove_plant_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
