# Generated by Django 4.1.2 on 2023-11-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_plant_diary', '0006_remove_plant_status_alter_task_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
